/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as OrderHistoryIndexRouteImport } from './routes/order-history/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutCollectionNameRouteImport } from './routes/_layout/$collectionName'
import { Route as LayoutProductsCategoryIndexRouteImport } from './routes/_layout/products/$category.index'
import { Route as LayoutProductsCategorySubcategoryIndexRouteImport } from './routes/_layout/products/$category.$subcategory.index'
import { Route as LayoutProductsCategorySubcategoryProductRouteImport } from './routes/_layout/products/$category.$subcategory.$product'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderHistoryIndexRoute = OrderHistoryIndexRouteImport.update({
  id: '/order-history/',
  path: '/order-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutCollectionNameRoute = LayoutCollectionNameRouteImport.update({
  id: '/$collectionName',
  path: '/$collectionName',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutProductsCategoryIndexRoute =
  LayoutProductsCategoryIndexRouteImport.update({
    id: '/products/$category/',
    path: '/products/$category/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutProductsCategorySubcategoryIndexRoute =
  LayoutProductsCategorySubcategoryIndexRouteImport.update({
    id: '/products/$category/$subcategory/',
    path: '/products/$category/$subcategory/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutProductsCategorySubcategoryProductRoute =
  LayoutProductsCategorySubcategoryProductRouteImport.update({
    id: '/products/$category/$subcategory/$product',
    path: '/products/$category/$subcategory/$product',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$collectionName': typeof LayoutCollectionNameRoute
  '/': typeof LayoutIndexRoute
  '/order-history': typeof OrderHistoryIndexRoute
  '/order': typeof OrderIndexRoute
  '/products/$category': typeof LayoutProductsCategoryIndexRoute
  '/products/$category/$subcategory/$product': typeof LayoutProductsCategorySubcategoryProductRoute
  '/products/$category/$subcategory': typeof LayoutProductsCategorySubcategoryIndexRoute
}
export interface FileRoutesByTo {
  '/$collectionName': typeof LayoutCollectionNameRoute
  '/': typeof LayoutIndexRoute
  '/order-history': typeof OrderHistoryIndexRoute
  '/order': typeof OrderIndexRoute
  '/products/$category': typeof LayoutProductsCategoryIndexRoute
  '/products/$category/$subcategory/$product': typeof LayoutProductsCategorySubcategoryProductRoute
  '/products/$category/$subcategory': typeof LayoutProductsCategorySubcategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/$collectionName': typeof LayoutCollectionNameRoute
  '/_layout/': typeof LayoutIndexRoute
  '/order-history/': typeof OrderHistoryIndexRoute
  '/order/': typeof OrderIndexRoute
  '/_layout/products/$category/': typeof LayoutProductsCategoryIndexRoute
  '/_layout/products/$category/$subcategory/$product': typeof LayoutProductsCategorySubcategoryProductRoute
  '/_layout/products/$category/$subcategory/': typeof LayoutProductsCategorySubcategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$collectionName'
    | '/'
    | '/order-history'
    | '/order'
    | '/products/$category'
    | '/products/$category/$subcategory/$product'
    | '/products/$category/$subcategory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$collectionName'
    | '/'
    | '/order-history'
    | '/order'
    | '/products/$category'
    | '/products/$category/$subcategory/$product'
    | '/products/$category/$subcategory'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$collectionName'
    | '/_layout/'
    | '/order-history/'
    | '/order/'
    | '/_layout/products/$category/'
    | '/_layout/products/$category/$subcategory/$product'
    | '/_layout/products/$category/$subcategory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  OrderHistoryIndexRoute: typeof OrderHistoryIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-history/': {
      id: '/order-history/'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof OrderHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/$collectionName': {
      id: '/_layout/$collectionName'
      path: '/$collectionName'
      fullPath: '/$collectionName'
      preLoaderRoute: typeof LayoutCollectionNameRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/products/$category/': {
      id: '/_layout/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof LayoutProductsCategoryIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/products/$category/$subcategory/': {
      id: '/_layout/products/$category/$subcategory/'
      path: '/products/$category/$subcategory'
      fullPath: '/products/$category/$subcategory'
      preLoaderRoute: typeof LayoutProductsCategorySubcategoryIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/products/$category/$subcategory/$product': {
      id: '/_layout/products/$category/$subcategory/$product'
      path: '/products/$category/$subcategory/$product'
      fullPath: '/products/$category/$subcategory/$product'
      preLoaderRoute: typeof LayoutProductsCategorySubcategoryProductRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutCollectionNameRoute: typeof LayoutCollectionNameRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProductsCategoryIndexRoute: typeof LayoutProductsCategoryIndexRoute
  LayoutProductsCategorySubcategoryProductRoute: typeof LayoutProductsCategorySubcategoryProductRoute
  LayoutProductsCategorySubcategoryIndexRoute: typeof LayoutProductsCategorySubcategoryIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutCollectionNameRoute: LayoutCollectionNameRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProductsCategoryIndexRoute: LayoutProductsCategoryIndexRoute,
  LayoutProductsCategorySubcategoryProductRoute:
    LayoutProductsCategorySubcategoryProductRoute,
  LayoutProductsCategorySubcategoryIndexRoute:
    LayoutProductsCategorySubcategoryIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  OrderHistoryIndexRoute: OrderHistoryIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
